<?xml version="1.0" encoding="utf-8"?>
<D:propertyupdate
xmlns:D="DAV:"
xmlns:Z="urn:schemas-microsoft-com:">
<D:set>
    <D:prop>
        <Z:Win32CreationTime>
            Thu, 02 Jul 2009 11:28:59 GMT
            </Z:Win32CreationTime>
        <Z:Win32LastAccessTime>
            Thu, 02 Jul 2009 11:28:59 GMT
            </Z:Win32LastAccessTime>
        <Z:Win32LastModifiedTime>
            Thu, 02 Jul 2009 11:28:59 GMT
            </Z:Win32LastModifiedTime>
        <Z:Win32FileAttributes>
            00000020
            </Z:Win32FileAttributes>
        </D:prop>
    </D:set>
</D:propertyupdate>
